# Generated by Django 4.2.21 on 2025-05-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_type', models.CharField(choices=[('INCENTIVE', 'incentive'), ('RIDE_FEE', 'ride_fee')], max_length=10)),
                ('income', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('ride_status', models.CharField(choices=[('R', 'Requested'), ('A', 'Approved'), ('C', 'Completed'), ('W', 'Withdrawn')], max_length=1)),
                ('pickup_location', models.TextField()),
                ('drop_location', models.TextField()),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(max_length=122)),
                ('vehicle_name', models.CharField(blank=True, max_length=122, null=True)),
                ('colour', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
