# Generated by Django 4.2.21 on 2025-05-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_vehicletype_alter_driverincome_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_cancellation', to='ride.ride')),
            ],
        ),
    ]
