# Generated by Django 4.2.21 on 2025-05-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
